#######################
### Calculate Price ###
#######################
### 1. Продукт без купона
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456790",
  "couponCode": ""
}

### 2. Продукт с фикс. купоном 50 eur
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456790",
  "couponCode": "COUPON2"
}

### 3. Продукт с % купоном 23 %
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456790",
  "couponCode": "COUPON3"
}

### 4. Продукт не существует
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 666,
  "taxNumber": "DE123456790",
  "couponCode": "COUPON3"
}

### 5. Купон не существует
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456790",
  "couponCode": "COUPON111"
}

### 6. Номер неправильный
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "IT12345678",
  "couponCode": "COUPON1"
}

########################
### Execute Purchase ###
########################
### 1. Paypal покупка OK
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "IT12345678000",
  "paymentProcessor": "paypal"
}

### 2. Paypal покупка FAIL
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 4,
  "taxNumber": "IT12345678000",
  "paymentProcessor": "paypal"
}

### 3. Stripe покупка OK
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 4,
  "taxNumber": "IT12345678000",
  "paymentProcessor": "stripe"
}

### 4. Stripe покупка FAIL
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 2,
  "taxNumber": "IT12345678000",
  "paymentProcessor": "stripe"
}

### 5. Способ оплаты неправильный
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 2,
  "taxNumber": "IT12345678000",
  "paymentProcessor": "swift"
}
